[tool.poetry]
name = "python_flask"
version = "0.1.0"
description = ""
authors = ["Anton"]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
