"""empty message

Revision ID: 205452a84bbc
Revises: 
Create Date: 2023-11-04 17:11:53.804241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205452a84bbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email', sa.String(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'email')
    # ### end Alembic commands ###
